### ISSUE TITLE
Testing Party Bug: Can still access the forum page without any login, even if that's allowed still see a logout and profile button.

### ISSUE THREAD

**Issue by simarmehta** [gcivil-nyu-org/wed-fall24-team1#200]
### Forum Page Issue

**Steps to Reproduce:**

1. Log in to the application.
2. Navigate to the forum page and view the comments.
3. Log out of the application.
4. Manually enter the URL of the forum page into the browser's address bar.
5. Press Enter to access the forum page.

**Observed Behavior:**

- After logging out, the user can still access the forum page without being prompted to log in.
- The forum content, including comments and results, is visible despite not being logged in.
- The "Logout" and "Profile" functionalities are still displayed and accessible even though the user is not logged in.

**Screenshots:**

https://github.com/user-attachments/assets/12baea29-28e6-466d-b2bc-5ce0d160a6c3

**Expected Behavior:**

- After logging out, attempting to access the forum page should redirect the user to the login page or display an access denied message.
- The forum content should not be accessible without proper authentication.
- "Logout" and "Profile" functionalities should not be visible or accessible when the user is not logged in, in case the page is set to visible without logging in.

**Comment by omerfarukbasar** [comment]
@simarmehta In the future, we were planning on allowing people to at least access certain features while logged out such as **viewing** threads, so it is technically intentional. Posting is obviously disabled until you login. The only thing that I might see as a possible issue is the profile/logout still being visible while logged out. We will address that part in a future patch. Thanks for pointing that out.

**Comment by ahhcash** [comment]
This isa good catch! Will investigate! Thanks!

**Comment by ahhcash** [comment]
Looked into it! Adding a login button makes sense, will take it up as an enhancement Thanks @simarmehta
